-- MySQL Script generated by MySQL Workbench
-- 03/26/15 22:17:25
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bir_dwts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bir_dwts` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bir_dwts` ;

-- -----------------------------------------------------
-- Table `bir_dwts`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bir_dwts`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL,
  `auth_key` VARCHAR(32) NULL,
  `password_hash` VARCHAR(255) NULL,
  `password_reset_token` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `status` SMALLINT(6) NULL,
  `user_type` INT NULL,
  `created_at` TIMESTAMP NULL,
  `update_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bir_dwts`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bir_dwts`.`position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position_code` VARCHAR(45) NULL,
  `position_name` VARCHAR(45) NULL,
  `position_description` VARCHAR(45) NULL,
  `position_notes` TEXT NULL,
  `create_time` TIMESTAMP NULL DEFAULT current_timestamp,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `bir_dwts`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bir_dwts`.`section` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `section_code` VARCHAR(45) NULL,
  `section_name` VARCHAR(45) NOT NULL,
  `section_description` TEXT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `bir_dwts`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bir_dwts`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL,
  `auth_key` VARCHAR(32) NULL,
  `password_hash` VARCHAR(255) NULL,
  `password_reset_token` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `status` SMALLINT(6) NULL,
  `user_type` INT NULL,
  `created_at` TIMESTAMP NULL,
  `update_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bir_dwts`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bir_dwts`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `current_position` INT NOT NULL,
  `section_id` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT current_timestamp,
  `update_time` DATETIME NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_position1_idx` (`current_position` ASC),
  INDEX `fk_employee_division1_idx` (`section_id` ASC),
  INDEX `fk_employee_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_employee_position1`
    FOREIGN KEY (`current_position`)
    REFERENCES `bir_dwts`.`position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_division1`
    FOREIGN KEY (`section_id`)
    REFERENCES `bir_dwts`.`section` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bir_dwts`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `bir_dwts`.`company_agency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bir_dwts`.`company_agency` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_agency_code` VARCHAR(45) NULL,
  `company_agencyl_name` VARCHAR(45) NULL,
  `company_agency_description` TEXT NULL,
  `create_time` TIMESTAMP NULL DEFAULT current_timestamp,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `bir_dwts`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bir_dwts`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_lastname` VARCHAR(45) NULL,
  `customer_firstname` VARCHAR(45) NULL,
  `company_agency_id` INT NOT NULL,
  `customer_cell_phone` VARCHAR(45) NULL,
  `customer_email` VARCHAR(45) NULL,
  `customer_landline` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT current_timestamp,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_company_agency1_idx` (`company_agency_id` ASC),
  CONSTRAINT `fk_customer_company_agency1`
    FOREIGN KEY (`company_agency_id`)
    REFERENCES `bir_dwts`.`company_agency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `bir_dwts`.`document_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bir_dwts`.`document_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `document_category_name` VARCHAR(45) NULL,
  `document_category_description` TEXT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `bir_dwts`.`document_priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bir_dwts`.`document_priority` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `document_priority_name` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bir_dwts`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bir_dwts`.`document` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `document_tracking_number` VARCHAR(45) NULL,
  `document_name` VARCHAR(45) NULL,
  `document_description` VARCHAR(45) NULL,
  `document_target_date` DATE NULL,
  `document_category` INT NOT NULL,
  `document_priority_id` INT NOT NULL,
  `document_type` VARCHAR(45) NULL,
  `document_comment` VARCHAR(45) NULL,
  `employee_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `company_agency_id` INT NOT NULL,
  `document_image_front_page` BLOB NULL,
  `create_time` TIMESTAMP NULL DEFAULT current_timestamp,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_document_employee1_idx` (`employee_id` ASC),
  INDEX `fk_document_customer1_idx` (`customer_id` ASC),
  INDEX `fk_document_company_agency1_idx` (`company_agency_id` ASC),
  INDEX `fk_document_document_category1_idx` (`document_category` ASC),
  INDEX `fk_document_document_priority1_idx` (`document_priority_id` ASC),
  CONSTRAINT `fk_document_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `bir_dwts`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `bir_dwts`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_company_agency1`
    FOREIGN KEY (`company_agency_id`)
    REFERENCES `bir_dwts`.`company_agency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_document_category1`
    FOREIGN KEY (`document_category`)
    REFERENCES `bir_dwts`.`document_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_document_priority1`
    FOREIGN KEY (`document_priority_id`)
    REFERENCES `bir_dwts`.`document_priority` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `bir_dwts`.`station_desk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bir_dwts`.`station_desk` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `station_desk_code` VARCHAR(45) NULL,
  `station_desk_name` VARCHAR(45) NULL,
  `station_desk_notes` TEXT NULL,
  `create_time` TIMESTAMP NULL DEFAULT current_timestamp,
  `update_time` DATETIME NULL,
  `section_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_station_desk_division1_idx` (`section_id` ASC),
  CONSTRAINT `fk_station_desk_division1`
    FOREIGN KEY (`section_id`)
    REFERENCES `bir_dwts`.`section` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `bir_dwts`.`document_workflow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bir_dwts`.`document_workflow` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `document_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `station_desk_id` INT NOT NULL,
  `document_wokflow_comments` TEXT NULL,
  `document_wokflow_status` VARCHAR(45) NULL COMMENT 'Document Workflow Status' /* comment truncated */ /*- accepted in process
- delay pending resolution
- completed released to next station
- completed released to customer*/,
  `time_accepted` TIMESTAMP NULL,
  `time_released` TIMESTAMP NULL,
  `total_time_spent` TIME NULL,
  `create_time` TIMESTAMP NULL DEFAULT current_timestamp,
  `update_time` DATETIME NULL,
  `employee_id1` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_document_wokflow_document1_idx` (`document_id` ASC),
  INDEX `fk_document_wokflow_employee1_idx` (`employee_id` ASC),
  INDEX `fk_document_wokflow_station_desk1_idx` (`station_desk_id` ASC),
  INDEX `fk_document_workflow_employee1_idx` (`employee_id1` ASC),
  CONSTRAINT `fk_document_wokflow_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `bir_dwts`.`document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_wokflow_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `bir_dwts`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_wokflow_station_desk1`
    FOREIGN KEY (`station_desk_id`)
    REFERENCES `bir_dwts`.`station_desk` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_workflow_employee1`
    FOREIGN KEY (`employee_id1`)
    REFERENCES `bir_dwts`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `bir_dwts`.`station_desk_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bir_dwts`.`station_desk_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `station_desk_role_code` VARCHAR(45) NULL,
  `station_desk_role_name` VARCHAR(45) NULL,
  `station_desk_role_description` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT current_timestamp,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `bir_dwts`.`employee_has_station_desk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bir_dwts`.`employee_has_station_desk` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `station_desk_id` INT NOT NULL,
  `station_desk_role_id` INT NOT NULL,
  `created_time` TIMESTAMP NULL,
  `update_time` DATETIME NULL,
  INDEX `fk_employee_has_station_desk_station_desk1_idx` (`station_desk_id` ASC),
  INDEX `fk_employee_has_station_desk_employee_idx` (`employee_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_employee_has_station_desk_station_desk_role1_idx` (`station_desk_role_id` ASC),
  CONSTRAINT `fk_employee_has_station_desk_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `bir_dwts`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_station_desk_station_desk1`
    FOREIGN KEY (`station_desk_id`)
    REFERENCES `bir_dwts`.`station_desk` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_station_desk_station_desk_role1`
    FOREIGN KEY (`station_desk_role_id`)
    REFERENCES `bir_dwts`.`station_desk_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `bir_dwts`.`employee_has_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bir_dwts`.`employee_has_position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `position_id` INT NOT NULL,
  `employee_position_start_date` DATE NULL,
  `employee_position_end_date` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_has_position_position1_idx` (`position_id` ASC),
  INDEX `fk_employee_has_position_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_employee_has_position_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `bir_dwts`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_position_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `bir_dwts`.`position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
